1st task
js-tasks-ru/jsbasic-20220211_leeloo3m pull request #1
Opened 2022-02-06 09:49 UTC by leeloo3m

2022-02-06 09:49 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2022-02-08 18:23 UTC, leeloo3m commented
4 из 5 задач решила как сумела, а слово факториал на меня страх наводит со школы

2022-02-09 11:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-09 11:55 UTC, SinimaWath requested changes

2022-02-09 11:55 UTC, SinimaWath commented on 1-module/2-task/index.js
> + return name.length < 4 || name.includes(' ') || name == null ?
Результат операции name.length < 4 || name.includes(' ') || name == null - и так boolean. Нет необходимости в тернарном операторе, давай попробуем без него

2022-02-09 11:55 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  }
Этот код никогда не выполниться

2022-02-09 11:55 UTC, SinimaWath commented on 1-module/2-task/index.js
> + return name.length < 4 || name.includes(' ') || name == null ?
Попробуй вызвать функцию isValid(null)

2022-02-09 11:55 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  }
Попробуй вызвать usFirst('')

2022-02-09 11:55 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  str.substr(0, maxlength-1) + '...' : str;
Символ 3 точки скопируй из условия задачи :)

2022-02-09 12:51 UTC, leeloo3m commented
Во 2 задаче. Я поняла что если возвращаемое значение будет false то условие не выполнится. Но как блин проверить на пустую строку??? Я пробовала name.length != 0, name != null и тд. 09.02.2022, 14:56, "Vladik Tarasov" ***@***.***>:
@SinimaWath requested changes on this pull request.



In 1-module/2-task/index.js:
> @@ -10,7 +10,9 @@ function print(text) {
  * чтобы функция sayHello работала корректно
  */
 function isValid(name) {
-  // ваш код...
+ return name.length < 4 || name.includes(' ') || name == null ? 

Результат операции name.length < 4 || name.includes(' ') || name == null - и так boolean. Нет необходимости в тернарном операторе, давай попробуем без него



In 1-module/3-task/index.js:
> +  if (val == undefined) {
+    return '';
+  }

Этот код никогда не выполниться



In 1-module/5-task/index.js:
> @@ -1,3 +1,5 @@
 function truncate(str, maxlength) {
-  // ваш код...
+  return str.length > maxlength ?
+  str.substr(0, maxlength-1) + '...' : str;

Символ 3 точки скопируй из условия задачи :)



In 1-module/2-task/index.js:
> @@ -10,7 +10,9 @@ function print(text) {
  * чтобы функция sayHello работала корректно
  */
 function isValid(name) {
-  // ваш код...
+ return name.length < 4 || name.includes(' ') || name == null ? 

Попробуй вызвать функцию isValid(null)



In 1-module/3-task/index.js:
> +  if (val == undefined) {
+    return '';
+  }

Попробуй вызвать usFirst('')

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

2022-02-09 13:19 UTC, leeloo3m commented
Работает!!! Если сделать проверку на null первой в условии. Wtf sorry)09.02.2022, 14:56, "Vladik Tarasov" ***@***.***>:
@SinimaWath requested changes on this pull request.



In 1-module/2-task/index.js:
> @@ -10,7 +10,9 @@ function print(text) {
  * чтобы функция sayHello работала корректно
  */
 function isValid(name) {
-  // ваш код...
+ return name.length < 4 || name.includes(' ') || name == null ? 

Результат операции name.length < 4 || name.includes(' ') || name == null - и так boolean. Нет необходимости в тернарном операторе, давай попробуем без него



In 1-module/3-task/index.js:
> +  if (val == undefined) {
+    return '';
+  }

Этот код никогда не выполниться



In 1-module/5-task/index.js:
> @@ -1,3 +1,5 @@
 function truncate(str, maxlength) {
-  // ваш код...
+  return str.length > maxlength ?
+  str.substr(0, maxlength-1) + '...' : str;

Символ 3 точки скопируй из условия задачи :)



In 1-module/2-task/index.js:
> @@ -10,7 +10,9 @@ function print(text) {
  * чтобы функция sayHello работала корректно
  */
 function isValid(name) {
-  // ваш код...
+ return name.length < 4 || name.includes(' ') || name == null ? 

Попробуй вызвать функцию isValid(null)



In 1-module/3-task/index.js:
> +  if (val == undefined) {
+    return '';
+  }

Попробуй вызвать usFirst('')

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

2022-02-09 13:30 UTC, leeloo3m commented
Redone

2022-02-11 18:33 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-02-11 18:33 UTC, SinimaWath approved these changes

2022-02-11 18:34 UTC, merged