all that delete
js-tasks-ru/jsbasic-20220211_leeloo3m pull request #4
Opened 2022-02-15 10:07 UTC by leeloo3m

2022-02-15 10:08 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-15 12:31 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-15 12:34 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-15 12:43 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-16 12:49 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-16 13:00 UTC, SinimaWath requested changes

2022-02-16 13:00 UTC, SinimaWath commented on 2-module/3-task/index.js
> +const { sum, multiply } = require("lodash");
Зачем тебе это тут?

2022-02-16 13:00 UTC, SinimaWath commented on package.json
> +  "dependencies": {
Убери от сюда все зависимости, они не нужны

2022-02-17 09:29 UTC, SinimaWath requested changes

2022-02-17 09:29 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  .join(''));
этот join, должен быть после map

2022-02-17 09:29 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  .map((index, item) => index == 0 ? item : item[0].toUpperCase() + item.slice(1)
Тут все наоборот, первый аргумент - это item, второй index

2022-02-17 09:45 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-17 15:01 UTC, SinimaWath requested changes

2022-02-17 15:01 UTC, SinimaWath commented on 4-module/1-task/index.js
> +  let result = document.querySelector('ul');
Вот этого делать не нужно, сразу используй переменную ul

2022-02-19 10:39 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-19 11:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-19 12:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-19 20:21 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-20 08:28 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-02-20 10:45 UTC, SinimaWath approved these changes

2022-02-20 10:47 UTC, merged