6.3
js-tasks-ru/jsbasic-20220211_leeloo3m pull request #8
Opened 2022-03-16 11:08 UTC by leeloo3m

2022-03-16 11:09 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-16 13:50 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-17 15:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-17 16:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-18 10:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-18 11:05 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-18 13:01 UTC, SinimaWath requested changes

2022-03-18 13:01 UTC, SinimaWath commented on 6-module/3-task/index.js
> +  <img src="/assets/images/carousel/${this.slides[0].image}" class="carousel__img" alt="slide">
Количество slides - может быть разным, надо формировать через цикл шаблон

2022-03-18 13:01 UTC, SinimaWath commented on 7-module/1-task/index.js
> +  <nav class="ribbon__inner">
Чтобы сделать верстку надо использовать массив - this.categories

2022-03-18 13:01 UTC, SinimaWath commented on 7-module/1-task/index.js
> +);
все плохо с отступами, надо поправить

2022-03-18 13:01 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    let conteiner = document.querySelector('.container');
елемент должен создавать в конструкторе, а в open, просто добавлять класс.

Тем самым можно будет вызвать setTitle и setBody раньше

2022-03-18 13:01 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    document.removeEventListener('keydown', handle);
handle - находится в замыкании функции open, поэтому тут ошибка, так как нет такой переменной.

Надо handle вынести в метод

2022-03-18 17:47 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-19 19:09 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-20 11:25 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-21 06:02 UTC, SinimaWath requested changes

2022-03-21 06:02 UTC, SinimaWath commented on 6-module/3-task/index.js
> +     let id = event.target.parentNode.parentNode.parentNode.getAttribute('data-id');
Давай тут используем closest, для поиска елемента

2022-03-21 06:02 UTC, SinimaWath commented on 6-module/3-task/index.js
> +     let id = event.target.parentNode.parentNode.parentNode.getAttribute('data-id');
Для получения дата атрибутов, используй dataset https://learn.javascript.ru/attributes-and-custom-properties#svoystvo-dataset-data-atributy

2022-03-21 06:02 UTC, SinimaWath commented on 6-module/3-task/index.js
> +     let id = event.target.parentNode.parentNode.parentNode.getAttribute('data-id');
Также нет необходимости тут использовать event.target - такой подход, обычно используют в делегировании.

А тут ты напрямую вещаешь обработчик события на елементы `el`.

Поэтому стоит переписать на: `let id = el.closest('....')`

2022-03-22 11:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-22 12:09 UTC, SinimaWath requested changes

2022-03-22 12:09 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    this.escape();
Вешать обработчик события, надо добавлять когда открывается модальное окно, и удалять когда закрывается

2022-03-22 12:09 UTC, SinimaWath commented on 7-module/2-task/index.js
> +        let modal = document.querySelector('.modal');
Может быть такая ситуация, что не будет в ДОМЕ modal, надо это проверить

2022-03-22 12:09 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    modal.remove();
Тут тоже надо проверить, что modal может не быть

2022-03-22 13:35 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-23 17:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-25 12:00 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-25 13:07 UTC, SinimaWath requested changes

2022-03-25 13:07 UTC, SinimaWath commented on 7-module/3-task/index.js
> +    let a = `
нет необходимости во временной переменной `a`

2022-03-25 13:07 UTC, SinimaWath commented on 7-module/4-task/index.js
> +    let a = `
нет необходимости во временной переменной `a`

2022-03-25 13:07 UTC, SinimaWath commented on 7-module/3-task/index.js
> +  changeVolume() {
по умолчанию, слайд со значением value должен быть активным

2022-03-26 07:24 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-26 13:52 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-26 15:03 UTC, SinimaWath requested changes

2022-03-26 15:03 UTC, SinimaWath commented on 7-module/3-task/index.js
> +      }
Этот код лишний, они ничего не делает

2022-03-26 15:03 UTC, SinimaWath commented on 7-module/3-task/index.js
> +      let ss = this.elem.querySelector('.slider__steps').classList.add('slider__step-activ')
тут опечатка, должно быть: `slider__step-active`

2022-03-26 15:03 UTC, SinimaWath commented on 7-module/3-task/index.js
> +      let ss = this.elem.querySelector('.slider__steps').classList.add('slider__step-activ')
Весь код, который у тебя используется по определению активного slider__steps, надо вынести в метод и:
- Использовать в обработчике события по клику
- И вызвать сразу, как отрисовывается елемент, чтобы выставить slider__step-active - по-умолчанию

2022-03-26 15:03 UTC, SinimaWath commented on 8-module/1-task/index.js
> +    let cartIcon =document.querySelector('.cart-icon');
Тебе ничего из DOM, ни надо выбирать, по условию, надо изменить только: `this.elem`

2022-03-26 15:03 UTC, SinimaWath commented on 8-module/1-task/index.js
> +    if (scrollTop>cartTop) {
Тут есть в условии подсказка с готовым кодом https://learn.javascript.ru/taskbook/jsbasic-20220211/workspace/8-module/1-task#podskazka

2022-03-26 15:03 UTC, SinimaWath commented on 8-module/1-task/index.js
> +    let b = cartLeft-contRight;
Из всех величин, тебе нужен только: `container.getBoundingClientRect().right` - чтобы посчитать отступ left.

2022-03-26 15:03 UTC, SinimaWath commented on 8-module/2-task/index.js
> +    let noNuts = this.products.filter((item)=>item.nuts==`${this.filters.noNuts}`);
Все эти массивы category, maxSpiciness, vegetarian, noNuts - независимы и никак не повиляли на массив this.products.

2022-03-26 15:03 UTC, SinimaWath commented on 8-module/2-task/index.js
> +
в метод updateFilter, приходят фильтры, которые надо записать в this.filters: `this.filters = Object.assign(this.filters, filters)`

2022-03-26 18:05 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-27 07:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-27 14:21 UTC, SinimaWath requested changes

2022-03-27 14:21 UTC, SinimaWath commented on 7-module/3-task/index.js
> +      let spanB = this.elem.querySelector(`.slider__steps span:nth-child(${this.value+1})`).classList.add('slider__step-active');
по-умолчанию, надо добавлять не по клику.

`this.elem.querySelector(`.slider__steps span:nth-child(${this.value+1})`).classList.add('slider__step-active');`

2022-03-27 14:21 UTC, SinimaWath commented on 8-module/2-task/index.js
> +    }
Это сильное усложнение, давай без Object.entries.

Ты можешь простой пройтись по this.products, и исключить то, что не нужно:

```

const filteredProducts = [];

for (const product in this.products) {
  if() {
    continue;
  }
  
  if () {
      continue;
  }
  
  ...
}
for 
```

2022-03-27 20:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-28 08:38 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-28 14:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-28 15:18 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-28 19:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-29 10:34 UTC, SinimaWath requested changes

2022-03-29 10:34 UTC, SinimaWath commented on 8-module/1-task/index.js
> +    let initialTopCoord = this.elem.getBoundingClientRect().top + window.pageYOffset;
Это значение не обязательно вычислять каждый раз, достаточно рассчитать при первом вызове метода updatePosition().

2022-03-29 10:34 UTC, SinimaWath commented on 8-module/2-task/index.js
> +
Вот здесь надо:
Или
отрисовывать елемент
Или
filteredProducts.push(product)

2022-03-29 10:34 UTC, SinimaWath commented on 8-module/3-task/index.js
> +    obj.count = 1;
Лучше заменить на:
```
let obj = {
  product: product,
  count: 1
}
```

2022-03-29 17:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-31 12:43 UTC, SinimaWath requested changes

2022-03-31 12:43 UTC, SinimaWath commented on 8-module/1-task/index.js
> +    }
Тебе это тоже не нужно

2022-03-31 12:45 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-31 13:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-31 18:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-02 17:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-03 10:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-03 13:25 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-03 16:11 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-03 18:27 UTC, SinimaWath requested changes

2022-04-03 18:27 UTC, SinimaWath commented on 8-module/3-task/index.js
> +    }
Давай это уберем из задачи 8-3, тут это не нужно

2022-04-03 18:27 UTC, SinimaWath commented on 8-module/3-task/index.js
> +      cartItem.count++;
Тут ты не изменяешь елемент массива, а изменяешь только обьект cartItems.

Если нашли такой же елемент, то count, надо увеличивать у елемента массива, к примеру, по индексу: `this.cartItems[idx].count++`

2022-04-04 13:44 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-05 06:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-05 13:43 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-06 13:52 UTC, SinimaWath requested changes

2022-04-06 13:52 UTC, SinimaWath commented on 8-module/4-task/index.js
> +      },
Это не нужно тут указывать

2022-04-06 13:52 UTC, SinimaWath commented on 8-module/4-task/index.js
> +   .then(function(response){
А зачем тут используешь обычную функцию?

если будешь использзовать стрелочную, то у тебя будет this

2022-04-07 17:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-07 20:26 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-08 06:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-08 06:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-08 08:24 UTC, SinimaWath requested changes

2022-04-08 08:24 UTC, SinimaWath commented on 8-module/4-task/index.js
> +      productPrice.innerHTML = `€${cartItem.product.price.toFixed(2)}`;
Тут должно быть: `(cartItem.product.price * cartItem.count).toFixed(2)`

2022-04-08 09:50 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-08 10:44 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-04-08 16:59 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-04-08 19:20 UTC, SinimaWath approved these changes

2022-04-08 19:21 UTC, merged